# Generated by Django 5.2 on 2025-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.AddField(
            model_name='activeuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
