# Generated by Django 5.2 on 2025-04-11 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_remove_activeuser_user_activeuser_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeuser',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='activeuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeuser',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Команда/название проекта'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Уникальный код'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='name_mentor',
            field=models.CharField(max_length=150, verbose_name='ФИО наставника'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='post_mentor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность наставника'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='theme',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема работы'),
        ),
    ]
