# Generated by Django 5.2 on 2025-04-13 05:57

import django.core.validators
import django.db.models.deletion
import reg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_alter_activeuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('school', models.CharField(max_length=200, verbose_name='Школа')),
                ('team_name', models.CharField(blank=True, max_length=100, verbose_name='Название команды')),
                ('mentor_last_name', models.CharField(max_length=100, verbose_name='Фамилия наставника')),
                ('mentor_first_name', models.CharField(max_length=100, verbose_name='Имя наставника')),
                ('mentor_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество наставника')),
                ('mentor_position', models.CharField(max_length=100, verbose_name='Должность наставника')),
                ('consent_file', models.FileField(upload_to='consents/', verbose_name='Согласие')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=reg.models.generate_unique_code, editable=False, max_length=8, unique=True, verbose_name='Код верификации')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Код верификации',
                'verbose_name_plural': 'Коды верификации',
            },
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone'], name='reg_partici_phone_dee06c_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='reg_partici_email_3c2498_idx'),
        ),
        migrations.AddField(
            model_name='usercode',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='reg.participant', verbose_name='Участник'),
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
        migrations.DeleteModel(
            name='CategoryTheme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddIndex(
            model_name='usercode',
            index=models.Index(fields=['code'], name='reg_usercod_code_bae342_idx'),
        ),
        migrations.AddIndex(
            model_name='usercode',
            index=models.Index(fields=['telegram_username'], name='reg_usercod_telegra_60bd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='usercode',
            index=models.Index(fields=['is_verified'], name='reg_usercod_is_veri_58f797_idx'),
        ),
    ]
